#server:
  #port: 8888

spring:
  server:
    port: 8095
    acceptorThreadCount: 4
    minSpareThreads: 50
    maxSpareThreads: 50
    maxThreads: 1000
    maxConnections: 10000
    connectionTimeout: 10000
    protocol: org.apache.coyote.http11.Http11Nio2Protocol
    redirectPort: 443
    compression: on
    MaxFileSize: 300MB
    MaxRequestSize: 500MB

  security:
    user:
      name: root
      password: root
  datasource:
    #驱动配置信息
    url: jdbc:mysql://127.0.0.1:3306/ordercenter?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #连接池的配置信息
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,bean,test

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.demo.entity.Order

http:
  pool:
    max-totle: 200
    max-per-route: 20
    connect-request-timeout: 5000
    connect-timeout: 5000
    socket-timeout: 60000

#logging:
  #config: classpath:logback-spring-test.xml
  #level:
       #com.alibaba.druid: debug
       #com.example.demo.mapper: debug
       #org.mybatis: debug

param: 000default